name: Github Pages Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.20]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        working-directory: ./typing-trainer
        run: npm install && npm run build
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.4.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: typing-trainer/dist/typing-trainer # The folder the action should deploy. 
